### PR TITLE
fix(analytics): Fix custom data layer function

### LINKED ISSUE #2505: AngularFireAnalyticsModule not send data
### Version info

**Angular:** `9.1.11`
**Firebase:** `7.15.1`
**AngularFire:** `5.4.2`

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** Web

### How to reproduce these conditions
My config:
```
import {AngularFireAnalyticsModule, DEBUG_MODE, ScreenTrackingService, UserTrackingService} from '@angular/fire/analytics';

AngularFireAnalyticsModule

  providers: [
    ScreenTrackingService,
    UserTrackingService,
    {provide: DEBUG_MODE, useValue: true},
    {provide: REGION, useValue: 'europe-west1'}
  ]

```
I have measurementId in config.

But not send any data :/. i init more than 1 month.

image

Thnaks!

### PR DESCRIPTION
**Pull request by Capelinha**
Change arrow function to a normal function to use the arguments object as described in the gtag documentation. That way, analytics sends data back to Google again.

Fixes #2505

### Checklist

   - Issue number for this PR: #2505 
   - Docs included?: no
   - Test units included?: no
   - In a clean directory, `yarn install`, `yarn test` run successfully? yes

### Description

Since updating to version 6.0.1, analytics no longer sends data to the Firebase Console. Analyzing and debugging this lib I realized that the code that defines a custom datalayer in gtag has been changed from a normal function to an arrow function.
 
After some research I learned that 'arguments' is not an array, it is actually an object that behaves like an array and contains more information besides indexes. 

I'm not sure what the analytics need for this 'arguments' object, but I know that by making this change, the analytics sent the data back to the Console.

### CODE REVIEW

**Comment by jamesdaniels** [comment]
Great catch! I'll merge and cut in the next PR, thanks.

**Review by jamesdaniels — APPROVED** [review]

**Comment by jamesdaniels** [comment]
Cut in `6.0.3-canary.77a9a15`

File: src/analytics/analytics.ts [hunk 1]
```diff
@@ -65,10 +65,11 @@ export class AngularFireAnalytics {
...
     if (!analyticsInitialized) {
       if (isPlatformBrowser(platformId)) {
-        gtag = (window[GTAG_FUNCTION_NAME] as any) || ((...args: any[]) => {
-          (window[DATA_LAYER_NAME] as any).push(args);
-        });
         window[DATA_LAYER_NAME] = window[DATA_LAYER_NAME] || [];
+        // tslint:disable-next-line: only-arrow-functions
+        gtag = (window[GTAG_FUNCTION_NAME] as any) || (function(..._args: any[]) {
+          (window[DATA_LAYER_NAME] as any).push(arguments);
+        });
```
Comment (Splaktar) [inline src/analytics/analytics.ts:72]: We really should have a comment in here that warns developers/contributors to making this an arrow function causes GA to break completely.

In the current state, it's likely that someone will come in and "fix" this breaking GA again.

**Comment by Splaktar** [comment]
For reference, this regression was introduced in https://github.com/angular/angularfire/commit/23e2f1e2e3909fd07c8f56106226e69a2514e6b5.

File: src/analytics/analytics.ts (hunk 1 above)
Comment (Capelinha) [reply src/analytics/analytics.ts:72]: You are right, I can make and submit another PR when I have free time
